dbt_medallion:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/runner/work/dbt_skeleton/dbt_skeleton/dbt_medallion/dbt_runner.json
      location: EU
      method: service-account
      priority: interactive
      project: ip-trabajo-gverdugo
      threads: 32
      type: bigquery
  target: dev
