version: 2
sources:
- name: bronze
  description: Dataset bronze in BigQuery.
  database: ip-trabajo-gverdugo
  schema: bronze
  tables:
  - name: sales
    description: Table sales from the bronze dataset.
    columns:
    - name: Row ID
      description: ''
      type: INT64
    - name: Order ID
      description: ''
      type: STRING
    - name: Order Date
      description: ''
      type: DATE
    - name: Ship Date
      description: ''
      type: DATE
    - name: Ship Mode
      description: ''
      type: STRING
    - name: Customer ID
      description: ''
      type: STRING
    - name: Customer Name
      description: ''
      type: STRING
    - name: Segment
      description: ''
      type: STRING
    - name: Country
      description: ''
      type: STRING
    - name: City
      description: ''
      type: STRING
    - name: State
      description: ''
      type: STRING
    - name: Postal Code
      description: ''
      type: INT64
    - name: Region
      description: ''
      type: STRING
    - name: Product ID
      description: ''
      type: STRING
    - name: Category
      description: ''
      type: STRING
    - name: Sub-Category
      description: ''
      type: STRING
    - name: Product Name
      description: ''
      type: STRING
    - name: Sales
      description: ''
      type: FLOAT64
