version: 2

sources:
  - name: bronze
    description: "Raw data dataset"
    schema: bronze
    tables:
      - name: sales
        description: "Sales table"
        columns:
          - name: Row ID
            description: "Unique identifier for each record."
          - name: Order ID
            description: "Unique identifier for each order."
          - name: Order Date
            description: "Date when the order was placed."
          - name: Ship Date
            description: "Date when the order was shipped."
          - name: Ship Mode
            description: "Method used to ship the order."
          - name: Customer ID
            description: "Unique identifier for the customer."
          - name: Customer Name
            description: "Name of the customer."
          - name: Segment
            description: "Customer segment category."
          - name: Country
            description: "Country where the order was shipped."
          - name: City
            description: "City where the order was shipped."
          - name: State
            description: "State or province where the order was shipped."
          - name: Postal Code
            description: "Postal code for the shipping address."
          - name: Region
            description: "Geographic region where the order was shipped."
          - name: Product ID
            description: "Unique identifier for the product."
          - name: Category
            description: "Category of the product."
          - name: Sub-Category
            description: "Sub-category of the product."
          - name: Product Name
            description: "Name of the product."
          - name: Sales
            description: "Sales amount for the order."
